<?php

// Variables
return [
  "creatorName" => "NWB2B",
  "creatorUrl" => "NWB2B",
  "templateName" => "NWB2B",
  "templateSuffix" => " ",
  "templateVersion" => "3.0.0",
  "templateFree" => false,
  "templateDescription" => "NWB2B is a powerful and customizable e-commerce template designed for modern online stores. It offers a clean, responsive design with an easy-to-use interface, perfect for businesses of all sizes. Featuring a wide range of customizable options, including product displays, payment integration, and advanced admin features, NWB2B helps you create an online store that looks great and functions seamlessly.",
  "templateKeyword" => "",
  "licenseUrl" => "",
  "livePreview" => "",
  "productPage" => "",
  "support" => "",
  "moreThemes" => "",
  "ogTitle" => "NWB2B",
  "ogImage" => "",
  "ogType" => "product",
  "documentation" => "",
  "generator" => "",
  "changelog" => "",
  "repository" => "",
  "gitRepo" => "",
  "gitRepoAccess" => "",
  "githubFreeUrl" => "",
  "facebookUrl" => "",
  "twitterUrl" => "",
  "githubUrl" => "",
  "dribbbleUrl" => "",
  "instagramUrl" => "",
  "payment_status" => ["Due","Paid","Partial"],
  "order_status" => ["Completed"]
];
